# File Path: insightgen/docker-compose.yml

version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6338:6333"  # Using entirely new port 6338
      - "6339:6334" 
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongodb_data:
  qdrant_data: